### PR TITLE
Convert CoffeeScript to JavaScript

### PR DESCRIPTION
**Pull request by mftaff**
Hey guys, I am using rails 5 without coffescript installed.

Would it be possible to add this branch to the project so that people would have the option of installing the gem from the no-coffeescript branch?

Thanks!!

### CODE REVIEW

**Comment by rvanlieshout** [comment]
@shkm, this replaces our coffee script version. Do we want that? I guess there is no reason to have a dependency on coffee script for this small bit of code

**Comment by shkm** [comment]
Yeah, assuming it all works then I don't see why we'd want to use coffeescript in master either.

**Comment by mftaff** [comment]
@shkm I have been using the it and it seems to work, but I haven't done any kind of testing to ensure all cases. That may be a job better suited to someone who is more familiar with the source code :-)

**Comment by mftaff** [comment]
Side Note: the only change made was - converting the coffeescript to javascript. IE there should be no practical difference in terms of functionality.

**Comment by rvanlieshout** [comment]
I’ll update documentation and add this ASAP

**Pull request merged**
